### ISSUE TITLE
Implement structs

### ISSUE THREAD

**Issue by jaredeh** [RichardDMatthew/scull#2]
typedef struct 
{
    int count;
    uint64_t pfns[MAX_PFNCOUNT];
 } swaphints_request_t

typedef struct 
{
    int count;
    uint64_t returncodes[MAX_PFNCOUNT];
 } swaphints_response_t

While these are statically sized the 'count' field will enable us to signal how many elements if the array to process even if the ioctl transfers the whole list.

**Comment by RichardDMatthew** [comment]
just placed structs in swaphints.h for future use
